### ISSUE TITLE
All Insurgency 2014 map pack and DistrictR map 

### ISSUE THREAD

**Issue by Svpenthopia** [olli-e/ISRT#11]
Hi olli-e.  I know I can still type it in the Rcon Command at bottom.   But a lot easier.   If you could please add the above in the preset scroll with HC Security and Insurgents?  It's not there.  

Thanks in advance,
Sv
![2022-03-23 (2)](https://user-images.githubusercontent.com/68416888/159576789-31cfe0d0-4b1d-4214-9602-368821471889.png)

**Comment by olli-e** [comment]
I will put it on the list for the next update. You can change this for yourself, if you like. Download a DB Browsers [https://sqlitebrowser.org](https://sqlitebrowser.org), close ISRT and open the ISRT DB in it (found in your ISRT Installation folder under the folder "db" (Example for me was: "C:\Users\Madman\AppData\Local\ISRT_v1.5\db") 

![Capture](https://user-images.githubusercontent.com/70414281/159655205-73f6d767-1a0f-4c32-aab4-25bb39a6ef88.JPG)

Change into table "map_config" and filter for "Market". Now you have one entry and you go to the left, until you find the column "self_added" and you change the value to 1. Save and close the DB.

![Capture2](https://user-images.githubusercontent.com/70414281/159655209-b554bbe1-1d9e-4fdb-b815-0da7dba064a5.JPG)

As of now you can add scenarios as you like in the map manager of ISRT.

![Capture3](https://user-images.githubusercontent.com/70414281/159655411-44b756c2-8c03-449b-8cd6-700313f765f6.JPG)

Hope that helps for the moment!

**Comment by Svpenthopia** [comment]
Thanks olli-e.  I did add some map in the map manager before.  I forgot I can edit those current map inside the map manager.  I had done and update those map I requested earlier.  All working now.  Thanks again.  Appreciate you help.
