### ISSUE TITLE
ISRT Error Message: timed out

### ISSUE THREAD

**Issue by z4ch523** [olli-e/ISRT#12]
When I try to send a command to my server i always receive the following message:
![image](https://user-images.githubusercontent.com/69817479/162537825-dacfb227-f0c7-4988-bde0-9c33c234b91c.png)

The server details are correctly found when I enter the IP and the necessary ports. I also double checked, that the password is correct.
The query timeout is set to 2 seconds.

**Comment by olli-e** [comment]
HI, sorry for the late reply, I didn't receive a notification about it....could you send me the ip, ports and (a temporary) rcon password for me to check that to madmans@isrt.info ?
Thanks,
Madman

**Comment by z4ch523** [comment]
No worries. I think it was a misconfiguratiom of my game server running inside docker.
Thanks for this great tool!!!

**Comment by olli-e** [comment]
Worked out, Closed
