### ISSUE TITLE
Recon Tool Set up Issues

### ISSUE THREAD

**Issue by Dazbow** [olli-e/ISRT#16]
Hi,

I'm
![Capture](https://user-images.githubusercontent.com/114619310/192881645-d8f4b47d-90cd-49b0-b791-1b96d204d2d8.JPG)
 trying to set up a recon tool for my insurgency sandstorm server, I can see my server, see players and all info but when running a command, it comes up with an error. (See attached)

**Comment by olli-e** [comment]
Hi, I have seen that in a couple of cases now - a lot to be honest. And in 100% of all cases it was either:

- the wrong RCON Port
- RCON port was mixed together with Query port or
- Wrong password

Ir could of course also being a firewall in between, but that is more seldom the case. What was never the case is a malfunction in the software ;-) I can proudly say.

So please check your start script for the IP, Game, Query and RCON port - write them down and also set a new rcon password. Ensure that Game, Query and rcon port are not mixed or the same. That should most probably fix your problem. If not, get back to me please.
Cheers,
Olli
