### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by ViBrationNC** [olli-e/ISRT#17]
**fixed it.. thanks**  nice work btw! 

I need some help.. I downloaded installed and got it working last night.. now today.. I cannot connect. Got a discord for some screen sharing help?

**Comment by olli-e** [comment]
Hi, I have seen that in a couple of cases now - a lot to be honest. And in 100% of all cases it was either:

- the wrong RCON Port
- RCON port was mixed together with Query or game port or
- Wrong password

It could of course also being a firewall in between, but that is more seldom the case. What was never the case is, a malfunction in the software ;-) I can proudly say.

So please check your start script for the IP, Game, Query and RCON port - write them down and also set a new rcon password. Ensure that Game, Query and rcon port are not mixed or the same. That should most probably fix your problem. If not, get back to me please.
Cheers,
Olli
