### ISSUE TITLE
how to intall on linux 

### ISSUE THREAD

**Issue by Nomy61** [olli-e/ISRT#8]
hi olli do you have instructions on how to install on ubuntu desktop ty

**Comment by olli-e** [comment]
Hi Nomy,

I will get back to you tomorrow.

Best regards,
Olli

**Comment by Nomy61** [comment]
Thx olli

**Comment by olli-e** [comment]
Usually it should run with the command from the directory of the extracted ZIP-file (Python3 must be >= 3.8):

`python3 ./isrt.py`

If it doesn't ensure that python3 and PyQT5 is installed:

`sudo apt-get install python3 python3-pip python3-pyqt5`

If this doesn't help - further do:

```
python3 -m pip install --upgrade pip
pip3 uninstall PyQt5 PyQt5-plugins PyQt5-tools
pip3 install pyqt5==5.15.1 pyqt5-tools==5.15.1.3.0.2 requests psutil datetime pathlib pillow
```

Then this should work - if not, please paste the console response with the error code.

Madman

**Comment by Nomy61** [comment]
Thx madman

**Comment by Nomy61** [comment]
hi madman heres what im getting just so u know im not a linux guru im new to it but this is what im getting when i try this im not sure if im doing everything right

xxxxxxxxxxx:~/Downloads/ISRT_v1.5$ ./isrt.py
bash: ./isrt.py: Permission denied
xxxxxxxxxxx:~/Downloads/ISRT_v1.5$ python3 ./isrt.py

Traceback (most recent call last):
  File "./isrt.py", line 340, in <module>
    mgui = maingui()
  File "./isrt.py", line 217, in __init__
    self.gui.setupUi(self)
  File "/home/xxxxxx/Downloads/ISRT_v1.5/bin/isrt_gui.py", line 2255, in setupUi
    self.retranslateUi(ISRT_Main_Window)
  File "/home/xxxxxx/Downloads/ISRT_v1.5/bin/isrt_gui.py", line 2266, in retranslateUi
    self.dropdown_select_server.setPlaceholderText(_translate("ISRT_Main_Window", "Select Server"))
AttributeError: 'QComboBox' object has no attribute 'setPlaceholderText'
xxxxxxxxxxx:~/Downloads/ISRT_v1.5$
xxxxxxxxxxx:~/Downloads/ISRT_v1.5$
xxxxxxxxxxx:~/Downloads/ISRT_v1.5$

i might not  be doing this right

**Comment by Nomy61** [comment]
nevermind i got it to work thx

**Comment by Nomy61** [comment]
not sure whats up but 3 servers wont accept map changes or any kind of input but they do show up on the tool 

and i have another 4 with gtx gaming and im able to to make input changes the 3 servers that wont accept input commands is on my home linux server do i need to open a port for the rcon tool ?

**Comment by Nomy61** [comment]
![Screenshot from 2022-01-31 13-13-21](https://user-images.githubusercontent.com/47922910/151849844-805a5dd5-0d13-48e2-a56c-5c408b435ceb.png)

seems like the tool connects but it wont accept any commands or inputs is server is on my linux box at home

**Comment by olli-e** [comment]
You need for query UDP 27133 incoming, for rcon TCP 27016 incoming open in your firewall, otherwise it won't work. We can always make a desktop sharing session to find the error together, if you like, but yeah, networking requirements must be met upfront ;-)

**Comment by Nomy61** [comment]
kidda odd those ports r open on the server and i just opened them on my
ubuntu on my laptop and still no go

**Comment by Nomy61** [comment]
weird im able to imput cannds on 1 of the 3 servers i did open all nessasary ports could it be an ip issue cause all servers run off same ip

**Comment by olli-e** [comment]
Could you send me a temp rcon pw to my mailaddress madman-at-isrt.info? So I can give it a try and see if things work - Query works perfect for now on the server listed in aboves screenshot.

**Comment by Nomy61** [comment]
yep

**Comment by olli-e** [comment]
You have three servers running on that machine - did I get it right, that it doesn't work on all three servers - query OK but RCON doesn't?

**Comment by Nomy61** [comment]
yep
im redoing my firewall give me a min

**Comment by Nomy61** [comment]
is use admin wrapper to run the servers via ubuntu 20.04 

id BG-1 ip 76.66.126.202 qport 27135 rport 27017 pass test123

**Comment by Nomy61** [comment]
whats your email address

**Comment by Nomy61** [comment]
yes whats your email ill send access info

**Comment by olli-e** [comment]
madman-at-isrt.info

**Comment by Nomy61** [comment]
this is what i get when i try to email you
The address "madman-at-isrt.info" in the "To" field was not recognized. Please make sure that all addresses are properly formed.

**Comment by olli-e** [comment]
;-) you have to replace the -at- with the @ sign

**Comment by Nomy61** [comment]
> madman-at-isrt.info

**Comment by olli-e** [comment]
RCON works from my side for 76.66.126.202 with rcon port 27017 and test123 - I can list maps and that means, rcon works. Map change works, but the server doesn't change to BAB e.g., but that's not an ISRT issue - you have to look inot the server log to see what troubles it.

**Comment by Nomy61** [comment]
> ;-) you have to replace the -at- with the @ sign

shit lol

**Comment by olli-e** [comment]
You don't want to have your full mail address be written on a publicly reachable site for protection from spam reasons ;-) That's why I replaced it...

**Comment by Nomy61** [comment]
ok

**Comment by Nomy61** [comment]
thx could network security thing i need to do due to being on the same network thx for your assistance

**Comment by olli-e** [comment]
e.g. this doesn't work:
id BG-1 ip 76.66.126.202   qport 27135 rport 27017

This works:
id BG-1 ip 76.66.126.202   qport 27135 rport 27016

**Comment by Nomy61** [comment]
these r my port settings for the 3 servers
allow 27014/tcp
allow 27015/tcp
allow 27016/tcp
allow 27017/tcp
allow 27102/udp
allow 27104/udp
allow 27106/udp
allow 27131/udp
allow 27133/udp
allow 27135/udp

**Comment by Nomy61** [comment]
wont take anymore of your time thx for your imput

**Comment by olli-e** [comment]
No problem, I try to help. Check the settings on your router if NAT-ing is enabled for all these ports, otherwise the IP package can reach your server, but it doesn't know the way back. The config for 27017 needs to be the same as for port 27016, since I can rcon into port 27016, but not 27017. Perhaps you might want to change you rcon pws to different ones for all servers, so you actually know to which you are connected ;-) Please ensure the startscripts refelect the correct ports - I used SAW myself and it is really agreat help, but doesn't complain in case of double port usage. You can also run a wireshark on your server and your client to analyze your IP packets and find the error, but that's advanced networking stuff. 

You could try and change the rcon port on the one working server (rcon 27016) to 27017 and see if that works - if not, your router or firewall are producing your headache.

**Comment by Nomy61** [comment]
i just made individual ports and that seemed  to work instead of allow
27015:27017
