### ISSUE TITLE
Rcon Tool cannot work well with multiple server

### ISSUE THREAD

**Issue by Svpenthopia** [olli-e/ISRT#9]
Hi,  
When I run 2 server eg first server S001 follow by 2nd server S002.  Both show up at the Rcon Tool window.  But every time whenever I change the settings for the 2nd server S002.  It runs the change at the first server instead the 2nd server.  Which means its not communicating with the 2nd server.  It will keep on screwing up this way till I re-run the both server and make sure I don't try to do any command on the 2nd server.  I can only go ingame and make any map change successfully.  Cannot use rcon tool.  How to resolve this issue?  Please advice.  Thanks

yusufmak@yahoo.com.sg 
![Ist server](https://user-images.githubusercontent.com/68416888/152674935-bf252cee-4aa3-4cee-b01e-d2491119f249.png)
![2nd server](https://user-images.githubusercontent.com/68416888/152674945-dc906c19-e27a-47f5-a2d3-906deed999bb.png)
[Sandstorm Batch file text.txt](https://github.com/olli-e/ISRT/files/8009861/Sandstorm.Batch.file.text.txt)

**Comment by olli-e** [comment]
HI there, it's not the tool that does anything wrong here, it's the user ;-) You have the same rcon port used for two different servers, that does not work. It's just random which server would react to the rcon command. You cannot use the same rcon port for two servers. You have to use different game, query and rcon ports for each server, then this will work without a problem.

Try using different ports for everything and then you'll see it works.

Get back to me, in case you still have problems, after you changed the ports.
Thanks,
Madman

**Comment by Svpenthopia** [comment]
> HI there, it's not the tool that does anything wrong here, it's the user ;-) You have the same rcon port used for two different servers, that does not work. It's just random which server would react to the rcon command. You cannot use the same rcon port for two servers. You have to use different game, query and rcon ports for each server, then this will work without a problem.
> 
> Try using different ports for everything and then you'll see it works.
> 
> Get back to me, in case you still have problems, after you changed the ports. Thanks, Madman

Oh, it works now after I change the rcon ports for the other server.  Appreciate the instant help.  Thank you so much.  

Btw.  All the previous version has a Donate link.  But it seems the link not working when I clicked on it.  This new version do not has the Donate link at all.  Any reason for taking off the link?

**Comment by olli-e** [comment]
Thanks for your support, I removed it, because there wasn't very much fo response and I'm not actively developing the software any further, just keeping it up-to-date and helping people. That's why I think, donation is no longer required. Thansk anyway!

**Comment by Svpenthopia** [comment]
Hi,
    No wonder every version.  I click the link nothing happen.  Its cleared up.  You had removed it.  It’s a good tool and useful to use.  You are very kind to develop this tool for public user.  Thanks again.
